version: '3.7'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:9999'
    environment:
      DATABASE_URL: postgres://username:password@db/app
    restart: unless-stopped
    depends_on:
      - db