[debug]
address = "0.0.0.0"
port = 9999

[release]
address = "0.0.0.0"
port = 9999
secret_key = "Dp8nFaRfpScS86md9cP8wvr3VrDuHHaTTN6g4QD8lmAzYpu85Jm3obPeMNRnZ2i9lxFqyPJVcVEt6Biq4d9HQP6k"

[default.limits]
forms = "64 kB"
json = "1 MiB"
msgpack = "2 MiB"
"file/jpg" = "5 MiB"

[global.oauth.google]
provider = "Google"
client_id = "321193948296-3fh4moft3ckhqmjrm951e4oks1s6psee.apps.googleusercontent.com"
client_secret = "6Ug0v6e4U_rXpXhF8Ebvp7xzwr0A"
redirect_uri = "https://sjr-home-manj.hogbisz.com/auth/google"

[global.oauth.hogbisz]
provider = "Hogbisz"
client_id = "sjr-home-manj"
client_secret = "uPNtw1PmuMaswGzCPRtdExomhYXXsPlc"
redirect_uri = "https://sjr-home-manj.hogbisz.com/auth/hogbisz"

[global.oauth.discord]
provider = "Discord"
client_id = "970888778426228756"
client_secret = "WSxmJT5Zs6YxvvDD7yGL-xGBmpnlZpvl"
redirect_uri = "https://sjr-home-manj.hogbisz.com/auth/discord"